DQN:
  gamma: 0.99
  learning_rate: 0.0003
  random_seed: 10
  buffer_size: 1000
  episodes: 100
  batch_size: 64
  log_interval: 10
  save_interval: 120
Env:
  time_limit: 10000
  evaluate_interval: 3
EpisodeMemory:
  batch_size: 4
  max_epi_num: 50
  max_seq_len: 400
  random_update: False
  lookup_size: 400